[package]
name = "codetriever-api"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "codetriever-api"
path = "src/main.rs"

[dependencies]
# Async runtime
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
async-trait = "0.1.89"

# Web framework
axum = { workspace = true }
tower = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging
log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Vector database
qdrant-client = { version = "1.15.0" }

# Embedding models
candle-core = { version = "0.9.1" }
candle-nn = { version = "0.9.1" }
candle-transformers = { version = "0.9.1" }
hf-hub = { version = "0.4.3", features = ["tokio"] }
tokenizers = { version = "0.22.0", default-features = false, features = ["onig"] }

[target.'cfg(target_os = "macos")'.dependencies]
candle-core = { version = "0.9.1", features = ["metal"] }
candle-nn = { version = "0.9.1", features = ["metal"] }
candle-transformers = { version = "0.9.1", features = ["metal"] }

# Code parsing
tree-sitter = "0.25.8"
tree-sitter-rust = "0.24.0"
tree-sitter-python = "0.23.6"
tree-sitter-javascript = "0.25.0"
tree-sitter-typescript = "0.23.2"
tree-sitter-go = "0.25.0"
tree-sitter-java = "0.23.5"
tree-sitter-cpp = "0.23.4"
tree-sitter-c = "0.24.1"
tree-sitter-c-sharp = "0.23.1"
tree-sitter-json = "0.24.8"
tree-sitter-xml = "0.7.0"
tree-sitter-yaml = "0.7.1"
tree-sitter-bash = "0.25.0"
tree-sitter-html = "0.23.2"
tree-sitter-powershell = "0.25.8"
tree-sitter-sequel = "0.3.8"

# Utils
lazy_static = "1.5.0"
walkdir = "2.5.0"
glob = "0.3.3"
ignore = "0.4.23"                                       # for .gitignore support
rayon = "1.11.0"                                       # for parallel processing
dashmap = "6.1.0"                                # concurrent hashmap
bytes = "1"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tower = { workspace = true }
once_cell = "1.20"

[lints]
workspace = true
