services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: codetriever-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ${HOME}/.codetriever/qdrant/storage:/qdrant/storage:z
    environment:
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  default:
    name: codetriever-network