version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: codetriever-qdrant
    ports:
      - "127.0.0.1:6333:6333"  # Only bind to localhost
      - "127.0.0.1:6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=WARN
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__MAX_REQUEST_SIZE_MB=256
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__STORAGE__SNAPSHOTS_PATH=/qdrant/snapshots
      - QDRANT__STORAGE__ON_DISK_PAYLOAD=true
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  api:
    image: codetriever/api:latest
    container_name: codetriever-api
    ports:
      - "127.0.0.1:8080:8080"  # Only bind to localhost
    environment:
      - RUST_LOG=warn
      - RUST_BACKTRACE=1
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=codetriever
      - EMBEDDING_MODEL=jinaai/jina-embeddings-v2-base-code
      - USE_METAL=false
      - MAX_CHUNK_SIZE=512
      - CHUNK_OVERLAP=50
    volumes:
      - api_cache:/app/cache
      - ${REPOS_PATH:-./repos}:/app/repos:ro
    depends_on:
      qdrant:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: codetriever-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: always
    profiles:
      - with-proxy

volumes:
  qdrant_data:
    driver: local
  api_cache:
    driver: local

networks:
  default:
    name: codetriever-network
    driver: bridge