services:
  postgres:
    image: postgres:16-alpine
    container_name: codetriever-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=codetriever
      - POSTGRES_PASSWORD=codetriever
      - POSTGRES_DB=codetriever
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
    volumes:
      - ${HOME}/.codetriever/postgres/data:/var/lib/postgresql/data:z
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codetriever"]
      interval: 5s
      timeout: 3s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: codetriever-qdrant
    ports:
      - "6333:6333"  # REST API port
      - "6334:6334"  # gRPC port (used by Rust client)
    volumes:
      - ${HOME}/.codetriever/qdrant/storage:/qdrant/storage:z
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  default:
    name: codetriever-network