name: CI

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Quick tests on push to main
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
      
      # Just run tests - no complex validation
      - name: Run tests
        run: cargo test
      
      # Quick format check
      - name: Check formatting
        run: cargo fmt -- --check
        continue-on-error: true  # Don't block on formatting